### ISSUE TITLE
Timer can't run on Ubuntu 20.10 anymore.

### ISSUE THREAD

**Issue by R-i-a-t-h** [NinjaSnail1080/mc-universal-in-game-timer#10]
I just installed Ubuntu 20.10 on a new pc and I installed this timer version 1.2.2 and it kept asking what loader I would like to launch it from. I tried everything I had and even WineHQ but nothing worked. On my older pc, I had installed version 1.2.1 and none of the issues were present (it simply said run, not run through _). I checked and for version 1.2.1 there is only the source code, not the downloads. Is there any way I can download version 1.2.1 until the issue is fixed?

P.S. OBS has the option to green-screen windows and make the backgrounds transparent. Can we get an option to change the background of the timer to lime-green so we can make it transparent in OBS? It would look much better for recording/streaming but it's not a big deal.

I can provide footage and screenshots from both pcs if it helps. My discord user is Riath#1700.

Update: I downloaded version 1.2.1 from my old pc to my new pc using google drive and it worked perfectly. I noticed that I uses a large portion of my CPU though.

**Comment by NinjaSnail1080** [comment]
Linux testing for the timer was pretty limited, so if it's not working it might be best to just download the Python source code and run it directly.

The CPU usage issue is something I'm working on, and the next update will address it. 

OBS has a feature called "Color Key", which you can use to specify any color to make transparent. If you set it to black and make the timer's opacity 100%, the timer background will be transparent in the video.
