### ISSUE TITLE
Soo, this timer doesn't support Windows 7?

### ISSUE THREAD

**Issue by etherealxx** [NinjaSnail1080/mc-universal-in-game-timer#11]
- [ ] 
![sdferer](https://user-images.githubusercontent.com/64251396/104418987-660f1d80-55aa-11eb-9244-017ff9fff52c.PNG)
![esfwerwqr](https://user-images.githubusercontent.com/64251396/104418998-6a3b3b00-55aa-11eb-8f7c-e2eb3d8f08ba.PNG)

**Comment by NinjaSnail1080** [comment]
Yeah, you have to be in Windows 10 to use it
