### ISSUE TITLE
Detected as virus by Windows Defender on Windows 10, prevented from launching

### ISSUE THREAD

**Issue by python-b5** [NinjaSnail1080/mc-universal-in-game-timer#12]

**Comment by NinjaSnail1080** [comment]
Exclude the exe file by following these instructions: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

When you click `Add an exclusion`, select `File` and browse to the exe file
