### ISSUE TITLE
StopIteration Error

### ISSUE THREAD

**Issue by skipiano** [NinjaSnail1080/mc-universal-in-game-timer#13]
I tried running the app on MacOS Big Sur but the application popped up with an error of "Minecraft Universal In-Game Timer Error", so I tried downloading the source code and tried running with the python code where I got this error:
```
Traceback (most recent call last):
  File "/Users/hi/Downloads/mc-universal-in-game-timer-1.2.2/main.py", line 40, in <module>
    SETTINGS.setValue("ResetTime", utils.get_pre17_igt(SETTINGS.value("MinecraftDirectory", utils.get_default_minecraft_dir())))
  File "/Users/hi/Downloads/mc-universal-in-game-timer-1.2.2/utils.py", line 37, in get_pre17_igt
    return next(i for i in pre17_stats["stats-change"] if "1100" in i)["1100"]
StopIteration
```

I resolved this by fixing utils.py, replacing

`return next(i for i in pre17_stats["stats-change"] if "1100" in i)["1100"]`

with

```
try:
    return next(i for i in pre17_stats["stats-change"] if "1100" in i)["1100"]
except StopIteraton:
    pass
```

**Comment by 8pxl** [comment]
"StopIteraton" shout be "StopIteration"
