### ISSUE TITLE
Results in program termination on launch MAC.OS High Sierra

### ISSUE THREAD

**Issue by realdavidrx** [NinjaSnail1080/mc-universal-in-game-timer#14]
![Screen Shot 2021-02-04 at 5 08 04 PM](https://user-images.githubusercontent.com/66091556/106975652-c3127500-670b-11eb-95b7-55a8cfd9b9a2.png)
Results in crash on start.
Nothing shows on console when opened.

**Comment by realdavidrx** [comment]
Does work when launching from the python source files. May be a issue with High Sierra, but i am stuck on High Sierra due to Apple discontinuing support for OpenGL.

**Comment by westeod** [comment]
I also ran into this same issue on High sierra

**Comment by Clem2B** [comment]
Can you explain how to run it from the python source file, I don't know how to do and I can't use it

**Comment by phild-fbo** [comment]
> Can you explain how to run it from the python source file, I don't know how to do and I can't use it

Normally it should do the job if you open up your terminal and type **_python path/to/the/pythonfile_**
Tho I always get python errors in some lines.

**Comment by Clem2B** [comment]
Same issue, I get python errors and I don't know how to solve we're stuck

**Comment by phild-fbo** [comment]
> Same issue, I get python errors and I don't know how to solve we're stuck
> 
> That's weird to only have this issue on High Sierra

I was able to get the python script running on Big Sur finally but not on High Sierra.
You need to install all requirements - it should work on Big Sur.
I am still looking how to get it running on High Sierra - if I have news I will let you know.

**Comment by Clem2B** [comment]
NinjaSnail told me that I had to repackage the python program with the packaging tool py2app in High Sierra to recreate the timer but I don't know how to do. Can you help me ?? Do you have an idea ??

**Comment by phild-fbo** [comment]
> NinjaSnail told me that I had to repackage the python program with the packaging tool py2app in High Sierra to recreate the timer but I don't know how to do. Can you help me ?? Do you have an idea ??

Yeah I spoke also with him. I was only able to build it on Big Sur. I get errors on High Sierra when i try to install **PyQt5** and **pynput==1.6.8** - tried to fix it but gave up after 3 hours ... sorry.

**Comment by phild-fbo** [comment]
> NinjaSnail told me that I had to repackage the python program with the packaging tool py2app in High Sierra to recreate the timer but I don't know how to do. Can you help me ?? Do you have an idea ??

Hello I have good news for us!
A friend of mine @tobosplace was able to make an executable for me which works (at least) on my High Sierra 10.13.6 - I just uploaded the executable for you -> https://workupload.com/file/rtaVuBcpzL6
I really hope it works for you aswell!

Cheers and enjoy your weekend! :)

**Comment by Clem2B** [comment]
It works perfectly. Thank you a lot for your help. See you on top of Speedrun.com scoreboard!

**Comment by phild-fbo** [comment]
> It works perfectly. Thank you a lot for your help. See you on top of Speedrun.com scoreboard!

Great that it works aswell for you! Much welcome!
Maybe not on top for me but somewhere there for sure. :)
