### ISSUE TITLE
Failed to execute script main

### ISSUE THREAD

**Issue by peter3027** [NinjaSnail1080/mc-universal-in-game-timer#18]
When i open the timer it tells me "Failed to execute main script" i click "ok" and it just closes. (obs: i'm on Windows 10)

**Comment by NinjaSnail1080** [comment]
Read the bottom of the README file. It says

> This also happens to some people on Windows. No one knows why it just doesn't work on some computers. Unfortunately, the only fix is to uncheck the `RTA Timer` box and use only the IGT Timer.
