### ISSUE TITLE
Open console or terminate

### ISSUE THREAD

**Issue by NONA1232** [NinjaSnail1080/mc-universal-in-game-timer#19]
When I open the app it gives me 2 options to open the console or terminate the app I don't know what to do.  My OS version is macOS bigsur

**Comment by NinjaSnail1080** [comment]
Did it start happening once you set hotkeys or turned on the RTA timer? Try doing what it says near the bottom of the [README page](https://github.com/NinjaSnail1080/mc-universal-in-game-timer/blob/master/README.md)

**Comment by NONA1232** [comment]
nope thx
