### ISSUE TITLE
Crashes the second ran on windows 10 

### ISSUE THREAD

**Issue by farzadyaghoobi75** [NinjaSnail1080/mc-universal-in-game-timer#20]
Hi. i have a windows 10 and i have this issue  that the second i opne the .exe file a dialog opens which  says " failed to execute script main" and then it crashes. how can i try to fix this ?

**Comment by NinjaSnail1080** [comment]
Do what it says near the bottom of the [README](https://github.com/NinjaSnail1080/mc-universal-in-game-timer/blob/master/README.md) page

> This also happens to some people on Windows. No one knows why it just doesn't work on some computers. Unfortunately, the only fix is to uncheck the RTA Timer box and use only the IGT Timer.

**Comment by farzadyaghoobi75** [comment]
thanks somehow it worked .  @NinjaSnail1080
