### ISSUE TITLE
Error on first startup

### ISSUE THREAD

**Issue by gaato** [NinjaSnail1080/mc-universal-in-game-timer#23]
I have a similar problem with #19 . In my case, this is my first run and I haven't changed any hotkeys or other settings at all. My OS version is macOS Catalina 10.15.7. The application version is 1.3.0.

**Comment by gaato** [comment]
Of course, I haven't turned on the RTA timer yet because I haven't been able to start it.

**Comment by NinjaSnail1080** [comment]
The timer only works in Big Sur. I'll try and package it for older versions.

**Comment by gaato** [comment]
Thank you. I was just about to update about to Big Sur, so I will.

**Comment by gaato** [comment]
After updating to Big Sur, I was able to use the timer. Thank you.
