### ISSUE TITLE
Program crashes after using it.

### ISSUE THREAD

**Issue by K2erdnA** [NinjaSnail1080/mc-universal-in-game-timer#5]
I get the error
Fatal error detected
Failed to execute script main. What do I do
![s](https://user-images.githubusercontent.com/35741335/98076907-23461080-1eaa-11eb-80d5-b4a77bffa742.PNG)

**Comment by NinjaSnail1080** [comment]
Did this only start to happen once you set hotkeys? Also, do both the timer AND the error message show up or just the error message?

**Comment by fenixpsp** [comment]
Same thing happened to me, it was after I set the hotkeys. When I try to reopen it it shows up both the error and the timer.

**Comment by NinjaSnail1080** [comment]
Try running as admin and remove the hotkeys in settings

**Comment by fenixpsp** [comment]
I removed the hotkeys andd it works fine, only problem is that I cant use the hotkeys function... Is there any way for me to be able to use them?
Btw thx for the fast response

**Comment by NinjaSnail1080** [comment]
One person reported that he was able to reassign them and they suddenly started working. I don't know how that happened though.

The main problem is that for whatever reason, global hotkeys don't work for some people. I'm sure it has something to do with the `pynput` library that the app is using. Unfortunately, if hotkeys don't work for you there's no way around that. If you're on Windows, I'd recommend using Livesplit anyway.
