### ISSUE TITLE
Massive usage of CPU 

### ISSUE THREAD

**Issue by ghost** [NinjaSnail1080/mc-universal-in-game-timer#7]
When I open it, the timer consumes so much CPU that the fps drops like 20 or even more.
![Captura de Tela 2020-12-02 às 01 05 31](https://user-images.githubusercontent.com/75344916/100814856-863fae80-343a-11eb-9913-dda1adf8ed4d.png)
Sometimes can even double the %, it s impracticle to use with minecraft.

**Comment by Benw8888** [comment]
I have a similar problem, but much worse. The timer is using many times more CPU than google chrome uses to stream youtube videos- intuitively I don't understand how that happens:
[
<img width="934" alt="Screen Shot 2021-04-11 at 1 10 59 AM" src="https://user-images.githubusercontent.com/39271586/114293398-c277c100-9a63-11eb-9255-c953c29c31aa.png">
](url)

And this is what my activity monitor is like while playing minecraft:
<img width="832" alt="Screen Shot 2021-04-11 at 1 21 00 AM" src="https://user-images.githubusercontent.com/39271586/114293463-30bc8380-9a64-11eb-9a83-4b92d5c7fd48.png">

At times the timer uses more CPU than minecraft. Doesn't this seem wrong?

**Comment by NinjaSnail1080** [comment]
The latest version lets you change the timer update intervals, which will let you fix this problem
